/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DummyIndexRouteImport } from './routes/dummy/index'
import { Route as BuildIndexRouteImport } from './routes/build/index'
import { Route as DummyIdRouteImport } from './routes/dummy/$id'
import { Route as BuildIdRouteImport } from './routes/build/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyIndexRoute = DummyIndexRouteImport.update({
  id: '/dummy/',
  path: '/dummy/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIndexRoute = BuildIndexRouteImport.update({
  id: '/build/',
  path: '/build/',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyIdRoute = DummyIdRouteImport.update({
  id: '/dummy/$id',
  path: '/dummy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIdRoute = BuildIdRouteImport.update({
  id: '/build/$id',
  path: '/build/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/build/$id': typeof BuildIdRoute
  '/dummy/$id': typeof DummyIdRoute
  '/build/': typeof BuildIndexRoute
  '/dummy/': typeof DummyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/build/$id': typeof BuildIdRoute
  '/dummy/$id': typeof DummyIdRoute
  '/build': typeof BuildIndexRoute
  '/dummy': typeof DummyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/build/$id': typeof BuildIdRoute
  '/dummy/$id': typeof DummyIdRoute
  '/build/': typeof BuildIndexRoute
  '/dummy/': typeof DummyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/build/$id'
    | '/dummy/$id'
    | '/build/'
    | '/dummy/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/build/$id' | '/dummy/$id' | '/build' | '/dummy'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/build/$id'
    | '/dummy/$id'
    | '/build/'
    | '/dummy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  BuildIdRoute: typeof BuildIdRoute
  DummyIdRoute: typeof DummyIdRoute
  BuildIndexRoute: typeof BuildIndexRoute
  DummyIndexRoute: typeof DummyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy/': {
      id: '/dummy/'
      path: '/dummy'
      fullPath: '/dummy/'
      preLoaderRoute: typeof DummyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/': {
      id: '/build/'
      path: '/build'
      fullPath: '/build/'
      preLoaderRoute: typeof BuildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy/$id': {
      id: '/dummy/$id'
      path: '/dummy/$id'
      fullPath: '/dummy/$id'
      preLoaderRoute: typeof DummyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/$id': {
      id: '/build/$id'
      path: '/build/$id'
      fullPath: '/build/$id'
      preLoaderRoute: typeof BuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  BuildIdRoute: BuildIdRoute,
  DummyIdRoute: DummyIdRoute,
  BuildIndexRoute: BuildIndexRoute,
  DummyIndexRoute: DummyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
